language: rust
rust:
  - nightly
  - stable
branches:
  except:
    - staging.tmp

# Install ALSA development libraries before compiling on Linux.
addons:
  apt:
    packages:
        - libasound2-dev
